### ISSUE TITLE
missing dependency tslib

### ISSUE THREAD

**Issue by patte** [holdfenytolvaj/pogi#10]
[pgDb.js requires tslib](https://github.com/holdfenytolvaj/pogi/blob/master/lib/pgDb.js#L4), although it's missing in package.json.

```
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/pogi/lib/pgDb.js:4:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by garaboncias** [comment]
Thanks for the issue, 
I release a new version to fix it
